Repository jenkins-x/jxr-packs-kubernetes, pull requests merged in 2020-08, with the labels that each got.

#36 fix: add optional kaniko flags env var
  packs/C++/pipeline.yaml
  packs/D/pipeline.yaml
  packs/csharp/pipeline.yaml
  packs/cwp/pipeline.yaml
  packs/docker-helm/pipeline.yaml
  packs/docker/pipeline.yaml
  packs/go-cli/pipeline.yaml
  packs/go-mongodb/pipeline.yaml
  packs/go/pipeline.yaml
  packs/gradle/pipeline.yaml
  packs/javascript-ui-nginx/pipeline.yaml
  packs/javascript/pipeline.yaml
  packs/maven-node-ruby/pipeline.yaml
  packs/maven/pipeline.yaml
  packs/ml-python-gpu-service/pipeline.yaml
  packs/ml-python-service/pipeline.yaml
  packs/php/pipeline.yaml
  packs/python/pipeline.yaml
  packs/ruby/pipeline.yaml
  packs/rust/pipeline.yaml
  packs/scala/pipeline.yaml
Labels: size/M

#37 fix: add log step for the apply
  packs/environment-gitops/pipeline.yaml
Labels: size/XS

#38 fix: Add ingress defaults
  packs/python/charts/values.yaml
Labels: lgtm, ok-to-test, size/S
