Repository jenkins-x/jxr-packs-kubernetes, pull requests merged in 2020-09, with the labels that each got.

#39 fix: lets clear the old google credentials env var
  packs/C++/pipeline.yaml
  packs/D/pipeline.yaml
  packs/csharp/pipeline.yaml
  packs/cwp/pipeline.yaml
  packs/docker-helm/pipeline.yaml
  packs/docker/pipeline.yaml
  packs/go-cli/pipeline.yaml
  packs/go-mongodb/pipeline.yaml
  packs/go/pipeline.yaml
  packs/gradle/pipeline.yaml
  packs/javascript-ui-nginx/pipeline.yaml
  packs/javascript/pipeline.yaml
  packs/maven-node-ruby/pipeline.yaml
  packs/maven/pipeline.yaml
  packs/ml-python-gpu-service/pipeline.yaml
  packs/ml-python-service/pipeline.yaml
  packs/php/pipeline.yaml
  packs/python/pipeline.yaml
  packs/ruby/pipeline.yaml
  packs/rust/pipeline.yaml
  packs/scala/pipeline.yaml
Labels: size/M

#40 fix: remove the jxl images
  packs/C++/pipeline.yaml
  packs/D/pipeline.yaml
  packs/apps/pipeline.yaml
  packs/charts/pipeline.yaml
  packs/csharp/pipeline.yaml
  packs/cwp/pipeline.yaml
  packs/docker-helm/pipeline.yaml
  packs/docker/pipeline.yaml
  packs/environment-helmfile/pipeline.yaml
  packs/go-cli/pipeline.yaml
  packs/go-mongodb/pipeline.yaml
  packs/go/pipeline.yaml
  packs/gradle/pipeline.yaml
  packs/helm/pipeline.yaml
  packs/javascript-ui-nginx/pipeline.yaml
  packs/javascript/pipeline.yaml
  packs/maven-node-ruby/pipeline.yaml
  packs/maven/pipeline.yaml
  packs/ml-python-gpu-service/pipeline.yaml
  packs/ml-python-service/pipeline.yaml
  packs/php/pipeline.yaml
  packs/python/pipeline.yaml
  packs/ruby/pipeline.yaml
  packs/rust/pipeline.yaml
  packs/scala/pipeline.yaml
Labels: size/L

#43 fix: switch to the new `jx preview create` command
  packs/C++/pipeline.yaml
  packs/D/pipeline.yaml
  packs/csharp/pipeline.yaml
  packs/cwp/pipeline.yaml
  packs/go-mongodb/pipeline.yaml
  packs/go/pipeline.yaml
  packs/gradle/pipeline.yaml
  packs/javascript-ui-nginx/pipeline.yaml
  packs/javascript/pipeline.yaml
  packs/maven-node-ruby/pipeline.yaml
  packs/maven/pipeline.yaml
  packs/ml-python-gpu-service/pipeline.yaml
  packs/ml-python-service/pipeline.yaml
  packs/php/pipeline.yaml
  packs/python/pipeline.yaml
  packs/ruby/pipeline.yaml
  packs/rust/pipeline.yaml
  packs/scala/pipeline.yaml
Labels: size/M

#44 fix: migrate to helmfile previews
  packs/go/pipeline.yaml
  packs/go/preview/Chart.yaml
  packs/go/preview/Makefile
  packs/go/preview/README.md
  packs/go/preview/helmfile.yaml
  packs/go/preview/requirements.yaml
  packs/go/preview/values.yaml
  packs/go/preview/values.yaml.gotmpl
Labels: size/M

#45 fix: use correct preview dir
  packs/go/pipeline.yaml
Labels: size/XS

#46 fix: move the preview dir out of charts
  packs/go/pipeline.yaml
  packs/go/preview/README.md
  packs/go/preview/helmfile.yaml
Labels: size/S

#48 fix: add support for image pull secrets
  packs/C++/charts/templates/deployment.yaml
  packs/C++/charts/values.yaml
  packs/D/charts/templates/deployment.yaml
  packs/D/charts/values.yaml
  packs/appserver/charts/templates/deployment.yaml
  packs/appserver/charts/values.yaml
  packs/csharp/charts/values.yaml
  packs/cwp/charts/templates/deployment.yaml
  packs/cwp/charts/values.yaml
  packs/dropwizard/charts/templates/deployment.yaml
  packs/dropwizard/charts/values.yaml
  packs/go-mongodb/charts/templates/deployment.yaml
  packs/go-mongodb/charts/values.yaml
  packs/go/charts/templates/deployment.yaml
  packs/go/charts/values.yaml
  packs/gradle/charts/templates/deployment.yaml
  packs/gradle/charts/values.yaml
  packs/javascript-ui-nginx/charts/templates/deployment.yaml
  packs/javascript-ui-nginx/charts/values.yaml
  packs/javascript/charts/templates/deployment.yaml
  packs/javascript/charts/values.yaml
  packs/liberty/charts/templates/deployment.yaml
  packs/liberty/charts/values.yaml
  packs/maven-java11/charts/templates/deployment.yaml
  packs/maven-java11/charts/values.yaml
  packs/maven-node-ruby/charts/templates/deployment.yaml
  packs/maven-node-ruby/charts/values.yaml
  packs/maven-quarkus/charts/templates/deployment.yaml
  packs/maven-quarkus/charts/values.yaml
  packs/maven/charts/templates/deployment.yaml
  packs/maven/charts/values.yaml
  packs/ml-python-gpu-service/charts/values.yaml
  packs/ml-python-gpu-training/charts/values.yaml
  packs/ml-python-service/charts/values.yaml
  packs/ml-python-training/charts/values.yaml
  packs/php/charts/templates/deployment.yaml
  packs/php/charts/values.yaml
  packs/python/charts/values.yaml
  packs/ruby/charts/templates/deployment.yaml
  packs/ruby/charts/values.yaml
  packs/rust/charts/templates/deployment.yaml
  packs/rust/charts/values.yaml
  packs/scala/charts/templates/deployment.yaml
  packs/scala/charts/values.yaml
  packs/swift/chart/values.yaml
  packs/typescript/charts/templates/deployment.yaml
  packs/typescript/charts/values.yaml
Labels: size/L

#49 fix: use better YAML for image pull secrets
  packs/C++/charts/templates/deployment.yaml
  packs/C++/charts/values.yaml
  packs/D/charts/templates/deployment.yaml
  packs/D/charts/values.yaml
  packs/appserver/charts/templates/deployment.yaml
  packs/appserver/charts/values.yaml
  packs/csharp/charts/values.yaml
  packs/cwp/charts/templates/deployment.yaml
  packs/cwp/charts/values.yaml
  packs/dropwizard/charts/templates/deployment.yaml
  packs/dropwizard/charts/values.yaml
  packs/go-mongodb/charts/templates/deployment.yaml
  packs/go-mongodb/charts/values.yaml
  packs/go/charts/templates/deployment.yaml
  packs/go/charts/values.yaml
  packs/go/preview/values.yaml.gotmpl
  packs/gradle/charts/templates/deployment.yaml
  packs/gradle/charts/values.yaml
  packs/javascript-ui-nginx/charts/templates/deployment.yaml
  packs/javascript-ui-nginx/charts/values.yaml
  packs/javascript/charts/templates/deployment.yaml
  packs/javascript/charts/values.yaml
  packs/liberty/charts/templates/deployment.yaml
  packs/liberty/charts/values.yaml
  packs/maven-java11/charts/templates/deployment.yaml
  packs/maven-java11/charts/values.yaml
  packs/maven-node-ruby/charts/templates/deployment.yaml
  packs/maven-node-ruby/charts/values.yaml
  packs/maven-quarkus/charts/templates/deployment.yaml
  packs/maven-quarkus/charts/values.yaml
  packs/maven/charts/templates/deployment.yaml
  packs/maven/charts/values.yaml
  packs/ml-python-gpu-service/charts/values.yaml
  packs/ml-python-gpu-training/charts/values.yaml
  packs/ml-python-service/charts/values.yaml
  packs/ml-python-training/charts/values.yaml
  packs/php/charts/templates/deployment.yaml
  packs/php/charts/values.yaml
  packs/python/charts/values.yaml
  packs/ruby/charts/templates/deployment.yaml
  packs/ruby/charts/values.yaml
  packs/rust/charts/templates/deployment.yaml
  packs/rust/charts/values.yaml
  packs/scala/charts/templates/deployment.yaml
  packs/scala/charts/values.yaml
  packs/swift/chart/values.yaml
  packs/typescript/charts/templates/deployment.yaml
  packs/typescript/charts/values.yaml
Labels: size/L

#50 fix: use a preview ingress
  packs/C++/preview/values.yaml.gotmpl
  packs/D/preview/values.yaml.gotmpl
  packs/csharp/preview/values.yaml.gotmpl
  packs/cwp/preview/values.yaml.gotmpl
  packs/dropwizard/preview/values.yaml.gotmpl
  packs/go-mongodb/preview/values.yaml.gotmpl
  packs/go/preview/values.yaml.gotmpl
  packs/gradle/preview/values.yaml.gotmpl
  packs/javascript-ui-nginx/preview/values.yaml.gotmpl
  packs/javascript/preview/values.yaml.gotmpl
  packs/liberty/preview/values.yaml.gotmpl
  packs/maven-java11/preview/values.yaml.gotmpl
  packs/maven-node-ruby/preview/values.yaml.gotmpl
  packs/maven-quarkus/preview/values.yaml.gotmpl
  packs/maven/preview/values.yaml.gotmpl
  packs/ml-python-gpu-service/preview/values.yaml.gotmpl
  packs/ml-python-gpu-training/preview/values.yaml.gotmpl
  packs/ml-python-service/preview/values.yaml.gotmpl
  packs/ml-python-training/preview/values.yaml.gotmpl
  packs/php/preview/values.yaml.gotmpl
  packs/python/preview/values.yaml.gotmpl
  packs/ruby/preview/values.yaml.gotmpl
  packs/rust/preview/values.yaml.gotmpl
  packs/scala/preview/values.yaml.gotmpl
  packs/typescript/preview/values.yaml.gotmpl
Labels: size/L

#51 fix: previews to have image pull secrets and unique ingress
  packs/C++/preview/helmfile.yaml
  packs/C++/preview/values.yaml.gotmpl
  packs/D/preview/helmfile.yaml
  packs/D/preview/values.yaml.gotmpl
  packs/csharp/preview/helmfile.yaml
  packs/csharp/preview/values.yaml.gotmpl
  packs/cwp/preview/helmfile.yaml
  packs/cwp/preview/values.yaml.gotmpl
  packs/dropwizard/preview/helmfile.yaml
  packs/dropwizard/preview/values.yaml.gotmpl
  packs/go-mongodb/preview/helmfile.yaml
  packs/go-mongodb/preview/values.yaml.gotmpl
  packs/go/preview/helmfile.yaml
  packs/go/preview/values.yaml.gotmpl
  packs/gradle/preview/helmfile.yaml
  packs/gradle/preview/values.yaml.gotmpl
  packs/javascript-ui-nginx/preview/helmfile.yaml
  packs/javascript-ui-nginx/preview/values.yaml.gotmpl
  packs/javascript/preview/helmfile.yaml
  packs/javascript/preview/values.yaml.gotmpl
  packs/liberty/preview/helmfile.yaml
  packs/liberty/preview/values.yaml.gotmpl
  packs/maven-java11/preview/helmfile.yaml
  packs/maven-java11/preview/values.yaml.gotmpl
  packs/maven-node-ruby/preview/helmfile.yaml
  packs/maven-node-ruby/preview/values.yaml.gotmpl
  packs/maven-quarkus/preview/helmfile.yaml
  packs/maven-quarkus/preview/values.yaml.gotmpl
  packs/maven/preview/helmfile.yaml
  packs/maven/preview/values.yaml.gotmpl
  packs/ml-python-gpu-service/preview/helmfile.yaml
  packs/ml-python-gpu-service/preview/values.yaml.gotmpl
  packs/ml-python-gpu-training/preview/helmfile.yaml
  packs/ml-python-gpu-training/preview/values.yaml.gotmpl
  packs/ml-python-service/preview/helmfile.yaml
  packs/ml-python-service/preview/values.yaml.gotmpl
  packs/ml-python-training/preview/helmfile.yaml
  packs/ml-python-training/preview/values.yaml.gotmpl
  packs/php/preview/helmfile.yaml
  packs/php/preview/values.yaml.gotmpl
  packs/python/preview/helmfile.yaml
  packs/python/preview/values.yaml.gotmpl
  packs/ruby/preview/helmfile.yaml
  packs/ruby/preview/values.yaml.gotmpl
  packs/rust/preview/helmfile.yaml
  packs/rust/preview/values.yaml.gotmpl
  packs/scala/preview/helmfile.yaml
  packs/scala/preview/values.yaml.gotmpl
  packs/typescript/preview/helmfile.yaml
  packs/typescript/preview/values.yaml.gotmpl
Labels: size/L

#52 fix: add jx-values.yaml
  packs/C++/preview/jx-values.yaml
  packs/csharp/preview/jx-values.yaml
  packs/cwp/preview/jx-values.yaml
  packs/dropwizard/preview/jx-values.yaml
  packs/go-mongodb/preview/jx-values.yaml
  packs/go/preview/jx-values.yaml
  packs/gradle/preview/jx-values.yaml
  packs/javascript-ui-nginx/preview/jx-values.yaml
  packs/javascript/preview/jx-values.yaml
  packs/liberty/preview/jx-values.yaml
  packs/maven-java11/preview/jx-values.yaml
  packs/maven-node-ruby/preview/jx-values.yaml
  packs/maven-quarkus/preview/jx-values.yaml
  packs/maven/preview/jx-values.yaml
  packs/ml-python-gpu-service/preview/jx-values.yaml
  packs/ml-python-gpu-training/preview/jx-values.yaml
  packs/ml-python-service/preview/jx-values.yaml
  packs/ml-python-training/preview/jx-values.yaml
  packs/php/preview/jx-values.yaml
  packs/python/preview/jx-values.yaml
  packs/ruby/preview/jx-values.yaml
  packs/rust/preview/jx-values.yaml
  packs/scala/preview/jx-values.yaml
  packs/typescript/preview/jx-values.yaml
Labels: size/L

#53 fix: use correct indentation
  packs/docker-helm/pipeline.yaml
Labels: size/M

#41 fix: prevent duplicated setVersion steps
  packs/javascript/pipeline.yaml
Labels: needs-ok-to-test, size/XS
